services:
  db:
    image: mysql:8.4.3
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: backend_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    expose:
      - '3308'
    networks:
      - test-network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  magical-grass:
    image: ${DOCKER_USERNAME}/magical-grass
    restart: always
    build: ./
    working_dir: /magical-grass
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/backend_db
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - '8090:8080'
    expose:
      - 3308
    command: mvn spring-boot:run
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
volumes:
  db_data:
